[WIP] [cpplint] Provide Sider's recommended set of rules
sider/sider-docs pull request #506
Opened 2020-09-30 02:20 UTC by suetsuguk

Related to https://github.com/sider/runners/pull/1505

2020-10-05 04:57 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
> __[remark-lint]__ Use the trailing `[]` on reference links ([view](https://sider.review/gh/repos/142577083/pulls/506#issue-4720618))
>
> <details>
>
> | Rule | Severity |
> | ---- | -------- |
> | `no-shortcut-reference-link` | `warn` |
>
> You can [close this issue](https://sider.review/gh/repos/142577083/pulls/506#issue-4720618) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

[^1] and [^2] are the footnote notations.

2020-10-05 04:58 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +[^1]: http://www.doi.ics.keio.ac.jp/research.html
> __[Goodcheck]__ Use `https://` instead of `http://` if available ([view](https://sider.review/gh/repos/142577083/pulls/506#issue-4720161))
>
> <details>
>
> | Rule |
> | ---- |
> | `sider.sider-docs.https_url` |
>
> You can [close this issue](https://sider.review/gh/repos/142577083/pulls/506#issue-4720161) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

以下の理由でこのIssueをクローズしました：
- When the URL does not support `https:`

2020-10-05 04:59 UTC, suetsuguk commented on docs/tools/cplusplus/cpplint.md
> +Sider provides our [recommended ruleset](https://github.com/sider/runners/blob/master/images/cpplint/sider_recommended_CPPLINT.cfg) for cpplint. If your repository does not include `CPPLINT.cfg`, the
> __[remark-lint]__ Link to https://github.com/sider/runners/blob/master/images/cpplint/sider_recommended_CPPLINT.cfg is dead ([view](https://sider.review/gh/repos/142577083/pulls/506#issue-4720609))
>
> <details>
>
> | Rule | Severity |
> | ---- | -------- |
> | `no-dead-urls` | `warn` |
>
> You can [close this issue](https://sider.review/gh/repos/142577083/pulls/506#issue-4720609) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

The link will be available when the PR is merged.

2020-10-05 05:19 UTC, suetsuguk commented
- As for the link on the footnote, I'm now asking professors for the proper link.
- I don't know where to put a new page about our recommended ruleset. Currently it is under the Getting Started page. Also I cannot find how to show the item on the sidebar.

![image](https://user-images.githubusercontent.com/36753697/95042718-ba863f80-0715-11eb-9c52-798bd90879d9.png)

2020-10-05 05:55 UTC, ybiquitous requested changes
Need to change also `sidebars.json`:

https://github.com/sider/sider-docs/blob/f4317bfc54660db95f383bf1a3b8f1ca0e80e51b/website/sidebars.json#L3

2020-10-05 06:02 UTC, sumyapp approved these changes

2020-10-05 06:04 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
Footnotes are not supported in GitHub. See https://github.com/github/markup/issues/498

2020-10-05 06:05 UTC, yykamei commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
I updated the line with the following suggestion. Please ignore if you're not comfortable with it.

```suggestion
Sider provides our recommended ruleset, which can reduce false positives. We've introduced our own automated classifier based on K-means machine learning algorithm. We've trained the classifier to classify which rules to be addressed or not by counting the number of fixed issues, which are reported in the previous commits, using a total of about 3.6 million commits over 1,000 popular OSS repositories. This study has been conducted in collaboration with Prof. Shingo TAKADA[^1] of Keio University in Kanagawa, Japan, and Prof. Masataka NAGURA[^2] of Nanzan University in Aichi, Japan.
```

2020-10-05 06:06 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
Please check the solution on:

https://github.com/sider/sider-docs/blob/5d5ad7a68c37e06e366ef7a03e86eaa167b0c8fc/docs/getting-started/permissions.md#L21

2020-10-05 06:14 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +Sider automatically applies our recommended ruleset for supported analysis tools when a configuration file doesn't exist in your repository. Since the recommended rulesets are available on our websit
[suggestion] Currently, we have "recommended ruleset" of some tools that does **not** supported the alogorithm described in this page, e.g. MeowCop:

https://github.com/sider/sider-docs/blob/5d5ad7a68c37e06e366ef7a03e86eaa167b0c8fc/docs/tools/ruby/rubocop.md#default-configuration-for-rubocop

So, I wonder this description may misleading users. Can you improve the description?

2020-10-06 04:31 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
Thank you for pointing out. Fixed. commit 00760ea74dea9bfbffe1e93f56b683c42f647b5f

2020-10-06 04:32 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +¹ http://www.doi.ics.keio.ac.jp/research.html
> __[Goodcheck]__ Use `https://` instead of `http://` if available ([view](https://sider.review/gh/repos/142577083/pulls/506#issue-4731805))
>
> <details>
>
> | Rule |
> | ---- |
> | `sider.sider-docs.https_url` |
>
> You can [close this issue](https://sider.review/gh/repos/142577083/pulls/506#issue-4731805) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

以下の理由でこのIssueをクローズしました：
- When the URL does not support `https:`

2020-10-06 04:37 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +² https://researchmap.jp/read0129611
Insert blank line between 1 and 2.

2020-10-06 04:41 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Sider automatically applies our recommended ruleset for supported analysis tools when a configuration file doesn't exist in your repository. Since the recommended rulesets are available on our websit
I have added a condition sentence "For certain analysis tools listed in ..." to emphasize only dedicated tools have the ruleset obtained by the algorithm. commit 7416171387b52a528743209d07ac0715ad7423c0

2020-10-06 04:45 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Static code analysis tool can improve the quality of your source-code because it ensures coding-style across a project and also detects possible coding errors without any test executions. However, st
Fixed. Because I also have merged suggestions from Prof. Takada and Nagura accordingly, not all of your suggestions are applied.

2020-10-06 04:46 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Sider provides our recommended ruleset which can reduce false positives. We introduce our own automated classifier based on K-means machine learning algorithm. We train the classifier to classify whi
Fixed. Because I also have merged suggestions from Prof. Takada and Nagura accordingly, not all of your suggestions are applied.

2020-10-06 04:51 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +² https://researchmap.jp/read0129611
Will you do it?

<img width="645" alt="image" src="https://user-images.githubusercontent.com/473530/95160260-0bac3700-07db-11eb-896c-7db81f05a54a.png">

https://deploy-preview-506--sider-docs.netlify.app/getting-started/recommended-rules

2020-10-06 04:53 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +² https://researchmap.jp/read0129611
Yes, I will.

2020-10-06 04:55 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +² https://researchmap.jp/read0129611
Also, it seems better to move the footnotes to move above the "## Analysis tools including recommended ruleset obtained by the algorithm" heading.

```
¹ http://www.doi.ics.keio.ac.jp/research.html

² https://researchmap.jp/read0129611

## Analysis tools including recommended ruleset obtained by the algorithm
```

2020-10-06 04:56 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +## Analysis tools including recommended ruleset obtained by the algorithm
[suggestion] This heading seems too long to me. How about changing it as follows?

<img width="342" alt="image" src="https://user-images.githubusercontent.com/473530/95160463-9ee56c80-07db-11eb-8145-64c4f69f87cd.png">

```suggestion
## Supported tools
```

2020-10-06 05:05 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +² https://researchmap.jp/read0129611
Or, cannot we just link the professor's names as follows?

```
[Prof. Shingo TAKADA](http://www.doi.ics.keio.ac.jp/research.html)
```

2020-10-06 05:12 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +For certain analysis tools listed in [Analysis tools including recommended ruleset obtained by the algorithm](#analysis-tools-including-recommended-ruleset-obtained-by-the-algorithm), Sider provides
[suggestion] Can we avoid the abbreviations as follows? It seems a bit hard to read.

- `Prof. Shingo TAKADA` -> `Professor Shingo TAKADA`
- `Assoc. Prof. Masataka NAGURA` -> `Associate Professor Masataka NAGURA`

Also, how about using a list as follows?

```
<blank line>

This study has been conducted in collaboration with the following people:

- Professor Shingo TAKADA of Keio University in Kanagawa, Japan
- Associate Professor Masataka NAGURA of Nanzan University in Aichi, Japan
```

2020-10-06 05:15 UTC, ybiquitous commented on docs/getting-started/recommended-rules.md
> +## Supported tools
Sorry, here is for the unification of the style:

```suggestion
## Supported Tools
```

2020-10-06 06:26 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +- [Prof. Shingo TAKADA](http://www.doi.ics.keio.ac.jp/research.html) of Keio University in Kanagawa, Japan
> __[Goodcheck]__ Use `https://` instead of `http://` if available ([view](https://sider.review/gh/repos/142577083/pulls/506#issue-4732544))
>
> <details>
>
> | Rule |
> | ---- |
> | `sider.sider-docs.https_url` |
>
> You can [close this issue](https://sider.review/gh/repos/142577083/pulls/506#issue-4732544) if no need to fix it. [Learn more](https://help.sider.review/getting-started/working-with-issues).
>
> </details>

以下の理由でこのIssueをクローズしました：
- When the URL does not support `https:`

2020-10-06 06:33 UTC, suetsuguk commented
@ybiquitous @yykamei After discussed with Kobo-san, we decided to truncate sentences as possible to make users read this page easily.

2020-10-06 06:37 UTC, ybiquitous approved these changes
Great 👏

2020-10-07 00:45 UTC, yykamei approved these changes
OK

2020-10-07 00:45 UTC, yykamei commented on docs/getting-started/recommended-rules.md
> +Static analysis with its default configuration typically reports many issues, and some of them don't fit your projects. Most analysis tools have the capability to let users to enable/disable analysis
I think "let" doesn't require "to."

```suggestion
Static analysis with its default configuration typically reports many issues, and some of them don't fit your projects. Most analysis tools have the capability to let users enable/disable analysis rules for users to avoid such "false positives." But, a huge amount of issues makes it difficult to manually verify all of them. For certain analysis tools listed in [Supported Tools](#supported-tools), Sider provides our recommended ruleset which can reduce false positives.
```

2020-10-07 01:11 UTC, suetsuguk commented on docs/getting-started/recommended-rules.md
> +Static analysis with its default configuration typically reports many issues, and some of them don't fit your projects. Most analysis tools have the capability to let users to enable/disable analysis
Thank you for pointing out. Fixed. commit f99a3d5cd2f2a4639318139682eefb64acdad24c

2020-10-07 01:11 UTC, suetsuguk commented
Thank you all for taking your time.

2020-10-07 04:11 UTC, merged