Add code quality documentation
sider/sider-docs pull request #630
Opened 2021-06-30 04:55 UTC by dev-yakuza

**This is a draft of the documentation. I need your help to finish this.**

I try to write the documentation about the `Inspections` tab. But it's difficult to write only the `Inspections` tab, so I wrote all features of the `Branches` tab in `Code Quality`.

I am not sure that the name of the documentation page(`Code Quality`) and the details of the documentation are good enough.

@suetsuguk
Could you give me any feedback and suggestion? 🙇‍♂️ 

- Related: https://github.com/sider/sider-docs/issues/613

2021-06-30 07:13 UTC, dev-yakuza commented
You can see the document on https://deploy-preview-630--sider-docs.netlify.app/getting-started/code-quality

2021-07-01 09:37 UTC, suetsuguk requested changes
Comparing with some related articles published so far, I have checked the usage of terms and commented dozens of suggested changes. Thank you.

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +For the code quality, we use `Metrics Code Clone`, `Metrics Complexity`, and `Metrics File Info` of the analysis tools in [Sider Runners](https://github.com/sider/runners)
```suggestion
Our analysis tools `Metrics Code Clone`, `Metrics Complexity`, and `Metrics File Info` of [Runners](https://github.com/sider/runners) are used to measure the code quality.
```

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +- Metrics File Info: this analysis tool makes the last committed time and total line of the code(LOC) in the file
```suggestion
- Metrics Code Clone: measures the code duplication
- Metrics Complexity: measures the complexity
- Metrics File Info: measures the lines of code(LOC)
```

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +All issues are generated from your [Analysis tools](../getting-started/repository-settings.md#tools) configuration.
```suggestion
- Other tools selected at [Analysis tools](../getting-started/repository-settings.md#tools): measure the number of issues 
```

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +| Objective-C | ◯                  | ◯                  |
```suggestion
| Objective-C | x                  | ◯                  |
```

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +The `Metrics Code Clone` and `Metrics Complexity` have the limitation of the languages. Check the following table. If you use not supported languages, the `Metrics Code Clone` and `Metrics Complexity
```suggestion
The `Metrics Code Clone` and `Metrics Complexity` have the limitation of the languages. Check the following table. The `Metrics Code Clone` and `Metrics Complexity` can't generate results for files of unsupported languages.
```

2021-07-01 09:37 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +| C++         | ◯                  | ◯                  |
✔️  and `-` instead of `o` and `x` could be better.

2021-07-02 00:39 UTC, dev-yakuza commented on docs/getting-started/code-quality.md
> +| Objective-C | ◯                  | ◯                  |
Doesn't PMD/CPD support `Objective-C`? :thinking:

![Screen Shot 2021-07-02 at 9 36 07](https://user-images.githubusercontent.com/42969906/124204075-2e287200-db19-11eb-9a0a-e75114a275e3.jpg)

2021-07-02 00:47 UTC, dev-yakuza commented
@suetsuguk 
Fixed reviews on https://github.com/sider/sider-docs/pull/630/commits/879566be57789c924cc484a977df2640542da748
Thanks!

2021-07-02 01:18 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +| Objective-C | ◯                  | ◯                  |
Our runner supports only 10 languages of them by default. The list is defined here;
- https://github.com/sider/runners/blob/8a730fb5a0d54b4cb65b2a88e7a5cde8543dd241/lib/runners/processor/pmd_cpd.rb#L44-L55
- https://help.sider.review/tools/others/pmd-cpd#language

2021-07-02 01:21 UTC, dev-yakuza commented on docs/getting-started/code-quality.md
> +| Objective-C | ◯                  | ◯                  |
Fixed it on https://github.com/sider/sider-docs/pull/630/commits/072c8dbcf5090b7f01aff8ed5160bd6d59d4d233
Thanks!

2021-07-02 02:51 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +![Sider dashboard](../assets/code-quality/sider-dashboard.jpg)
I'm a bit worried your name on the image. Can you edit the image to remove it? If you don't mind, keep it as is.

2021-07-02 02:58 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +Click the `Analyze` button on the right side of the branch that you want to analyze. After all analysis has been completed, you can see the issues and code metrics on the following tabs.
```suggestion
Click the `Analyze` button on the right side of the branch that you want to analyze. After all analysis has been completed, you can see the issues and code metrics on the results tabs described in the following sections.
```

There are no tabs in THIS section. So this could be a better explanation.

2021-07-02 02:59 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +On the `Files` tab, You can see the `Duplicates`, `Complexity`, `LOC`, `Issues` and `Last commit` for each file and directory.
```suggestion
On the `Files` tab, you can see the `Duplicates`, `Complexity`, `LOC`, `Issues` and `Last commit` for each file and directory.
```
typo.

2021-07-02 03:04 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +The `Inspections` tab visualizes the code quality of your entire repository. The charts on this tab show several code quality metrics versus how often code is changing (Churn). Plotted points on indi
```suggestion
The `Inspections` tab visualizes the code quality of your entire repository. The charts on this tab show several code quality metrics versus how often code is changing (Churn). Plotted points on individual chart indicate files and metrics. The points are limited to the highest 30 of churn values.
```
typo.

2021-07-02 03:07 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +You can click a point to see its file name and metrics values on the indication area above the charts.
```suggestion
You can click any point to see its file name and metrics values on the indication area above the charts.
```
typo.

2021-07-02 03:18 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +| Language    | Metrics Code Clone | Metrics Complexity |
How about list only languages Sider supports by our Analysis Tools?
Here are the candidates to remove from this table:
- Fortran
- GDScript
- Lua
- Objective-C
- Rust
- Scala
- TTCN-3

2021-07-02 04:20 UTC, dev-yakuza commented
@suetsuguk 
Fixed the reviews on https://github.com/sider/sider-docs/pull/630/commits/9197ea667baa7a972342e43b1236ffad375b3011
Thanks!

2021-07-02 06:11 UTC, suetsuguk commented on docs/getting-started/code-quality.md
> +![Sider dashboard](../assets/code-quality/sider-dashboard.jpg)
⬆️  How about this comment?
I have verified other changes. Thank you.

2021-07-02 06:28 UTC, dev-yakuza commented on docs/getting-started/code-quality.md
> +![Sider dashboard](../assets/code-quality/sider-dashboard.jpg)
@suetsuguk 
Thanks for your review!
I removed my personal account from the image on https://github.com/sider/sider-docs/pull/630/commits/4ee2c904660c3dfa48b7c9698d8c1e637fea7a42?short_path=500586e#diff-500586ed376eea7af39f94a2107e2d57e9ab9f0178f852352f5ab6cde33ac2c0

2021-07-02 06:46 UTC, suetsuguk approved these changes
Great article! Thank you.

2021-07-02 06:48 UTC, merged